# Generated by Django 4.0.3 on 2022-03-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='User Name')),
                ('email', models.CharField(max_length=30, verbose_name='email')),
                ('password', models.CharField(max_length=12, verbose_name='password ')),
            ],
        ),
    ]
