# Generated by Django 4.0.3 on 2022-03-19 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mainproperty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainproperty',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
