# Generated by Django 4.0.3 on 2022-04-04 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainproperty',
            name='image1',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainproperty',
            name='image2',
            field=models.ImageField(default=2, upload_to='images/'),
            preserve_default=False,
        ),
    ]
